Release 5.1.0-beta.1

diff --git a/stop b/stop
--- a/stop
+++ b/stop
@@ -1,18 +1,57 @@
 #!/bin/sh
 
 . ./.env
+if [ -n "${HA_NFS_DATA_DIRECTORY}" ]; then
+    . ${HA_NFS_DATA_DIRECTORY}/config/.env
+fi
 
-docker-compose version &> /dev/null
-if [ $? -eq 127 ]; then
-    podman-compose version &> /dev/null
-    if [ $? -eq 127 ]; then
-        echo "Could not find docker-compose or podman-compose"
-        exit 1;
+if [ -f /etc/redhat-release ] && [ `grep -c "Red Hat" /etc/redhat-release` -eq 1 ]; then  
+    if [ `grep -c "7.9" /etc/redhat-release` -ge 1 ]; then
+        docker compose version &> /dev/null
+        if [ $? -eq 127 ]; then
+            echo "Could not find docker compose"
+            exit 1;
+        else
+            if [ -z "${HA_IP_LIST}" ]; then
+                alias compose_command="docker compose -f docker-compose.yml"
+            else
+                alias compose_command="docker compose -f docker-compose-ha.yml"
+            fi
+        fi
     else
-        alias compose_command="podman-compose -f podman-compose-ha.yml"
+        podman-compose version &> /dev/null
+        if [ $? -eq 127 ]; then
+            echo "Could not find podman-compose"
+            exit 1;
+        else
+            if [ -z "${HA_IP_LIST}" ]; then
+                alias compose_command="podman-compose -f podman-compose.yml"
+            else
+                alias compose_command="podman-compose -f podman-compose-ha.yml"
+            fi
+        fi
     fi
 else
-    alias compose_command="docker-compose -f docker-compose-ha.yml"
+    docker compose version &> /dev/null
+    if [ $? -eq 127 ]; then
+        podman-compose version &> /dev/null
+        if [ $? -eq 127 ]; then
+            echo "Could not find docker compose or podman-compose"
+            exit 1;
+        else
+            if [ -z "${HA_IP_LIST}" ]; then
+                alias compose_command="podman-compose -f podman-compose.yml"
+            else
+                alias compose_command="podman-compose -f podman-compose-ha.yml"
+            fi
+        fi
+    else
+        if [ -z "${HA_IP_LIST}" ]; then
+            alias compose_command="docker compose -f docker-compose.yml"
+        else
+            alias compose_command="docker compose -f docker-compose-ha.yml"
+        fi
+    fi
 fi
 
 if [ -n "${HA_IP_LIST}" ]; then
@@ -20,6 +59,10 @@ if [ -n "${HA_IP_LIST}" ]; then
 
     RETURN=$?
     if [ $RETURN -eq 0 ]; then
+        compose_command exec -- rabbitmq-stats rabbitmq-queues delete_member cloudexchange_9 rabbit@$HA_CURRENT_NODE
+        compose_command exec -- rabbitmq-stats rabbitmq-queues delete_member cloudexchange_6 rabbit@$HA_CURRENT_NODE
+        compose_command exec -- rabbitmq-stats rabbitmq-queues delete_member cloudexchange_3 rabbit@$HA_CURRENT_NODE
+
         compose_command exec -- rabbitmq-stats rabbitmqctl stop_app
         compose_command exec -- rabbitmq-stats rabbitmqctl reset
     elif [ $RETURN -eq 1 ]; then
@@ -27,23 +70,4 @@ if [ -n "${HA_IP_LIST}" ]; then
     fi
 fi
 
-docker-compose version &> /dev/null
-if [ $? -eq 127 ]; then
-    podman-compose version &> /dev/null
-    if [ $? -eq 127 ]; then
-        echo "Could not find docker-compose or podman-compose"
-        exit 1;
-    else
-        if [ -z "${HA_IP_LIST}" ]; then
-            podman-compose -f podman-compose.yml down -v
-        else
-            podman-compose -f podman-compose-ha.yml down -v
-        fi
-    fi
-else
-    if [ -z "${HA_IP_LIST}" ]; then
-        docker-compose down -v
-    else
-        docker-compose -f docker-compose-ha.yml down -v
-    fi
-fi
+compose_command down -v
