Added podman support

diff --git a/stop b/stop
--- a/stop
+++ b/stop
@@ -1,3 +1,14 @@
 #!/bin/sh
 
-docker-compose stop
+docker-compose version &> /dev/null
+if [ $? -eq 127 ]; then
+    podman-compose version &> /dev/null
+    if [ $? -eq 127 ]; then
+        echo "Could not find docker-compose or podman-compose"
+        exit 1;
+    else
+        podman-compose -f podman-compose.yml down
+    fi
+else
+    docker-compose stop
+fi
