5.0.0 Release (#35)
* Added 4.2.0 related changes

* Added 5.0.0 related changes

diff --git a/stop b/stop
--- a/stop
+++ b/stop
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+. ./.env
+
 docker-compose version &> /dev/null
 if [ $? -eq 127 ]; then
     podman-compose version &> /dev/null
@@ -7,8 +9,41 @@ if [ $? -eq 127 ]; then
         echo "Could not find docker-compose or podman-compose"
         exit 1;
     else
-        podman-compose -f podman-compose.yml down
+        alias compose_command="podman-compose -f podman-compose-ha.yml"
     fi
 else
-    docker-compose stop
+    alias compose_command="docker-compose -f docker-compose-ha.yml"
+fi
+
+if [ -n "${HA_IP_LIST}" ]; then
+    ./replica_set --remove
+
+    RETURN=$?
+    if [ $RETURN -eq 0 ]; then
+        compose_command exec -- rabbitmq-stats rabbitmqctl stop_app
+        compose_command exec -- rabbitmq-stats rabbitmqctl reset
+    elif [ $RETURN -eq 1 ]; then
+        exit 0
+    fi
+fi
+
+docker-compose version &> /dev/null
+if [ $? -eq 127 ]; then
+    podman-compose version &> /dev/null
+    if [ $? -eq 127 ]; then
+        echo "Could not find docker-compose or podman-compose"
+        exit 1;
+    else
+        if [ -z "${HA_IP_LIST}" ]; then
+            podman-compose -f podman-compose.yml down
+        else
+            podman-compose -f podman-compose-ha.yml down -v
+        fi
+    fi
+else
+    if [ -z "${HA_IP_LIST}" ]; then
+        docker-compose stop
+    else
+        docker-compose -f docker-compose-ha.yml stop
+    fi
 fi
